version: '3'

services:
  nginx1:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./projet-1:/var/www/html
      - ./projet-1/Config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php1

  nginx2:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./projet-2:/var/www/html
      - ./projet-2/Config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php2

  php1:
    build: .
    volumes:
      - ./projet-1:/var/www/html
    links:
      - mysql

  php2:
    build: .
    volumes:
      - ./projet-2:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: